// Code generated by "stringer -type=UserLevel -output=command_string.go"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Anyone-0]
	_ = x[Moderator-1]
	_ = x[Owner-2]
}

const _UserLevel_name = "AnyoneModeratorOwner"

var _UserLevel_index = [...]uint8{0, 6, 15, 20}

func (i UserLevel) String() string {
	if i < 0 || i >= UserLevel(len(_UserLevel_index)-1) {
		return "UserLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UserLevel_name[_UserLevel_index[i]:_UserLevel_index[i+1]]
}
